name: temani
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  percent_indicator: ^4.2.2
  date_picker_timeline: ^1.2.3
  intl: ^0.17.0
  provider: ^6.0.3
  google_fonts: ^3.0.1
  path: ^1.8.1
  get: ^4.6.5
  firebase_core: ^1.20.0
  google_sign_in: ^5.4.0
  google_nav_bar: ^5.0.6
  font_awesome_flutter: ^10.1.0
  line_icons: ^2.0.1
  get_storage: 


dev_dependencies:
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_login.png"
  

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   #   - images/a_dot_burr.jpeg
   #   - images/a_dot_ham.jpeg

    - assets/images/logo_login.png
    - assets/images/Buah_kandungan_4.png
    - assets/images/Buah_kandungan_7.png
    - assets/images/Buah_kandungan_9.png
    - assets/images/Buah_kandungan_11.png
    - assets/images/Buah_kandungan_14.png
    - assets/images/Buah_kandungan_16.png
    - assets/images/Buah_kandungan_17.png
    - assets/images/Buah_kandungan_18.png
    - assets/images/Buah_kandungan_20.png
    - assets/images/Buah_kandungan_23.png
    - assets/images/Buah_kandungan_26.png
    - assets/images/Buah_kandungan_28.png
    - assets/images/Buah_kandungan_32.png
    - assets/images/Buah_kandungan_33.png
    - assets/images/Buah_kandungan_35.png
    - assets/images/Buah_kandungan_39.png
    - assets/images/
    - assets/icons/

 
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      - family: Open-Sans
        fonts:
          - asset: fonts/OpenSans-Regular.ttf
            weight: 900


      - family: Montserrat
        fonts:
          - asset: fonts/Montserrat-Black.ttf
          - asset: fonts/Montserrat-Light.ttf
          - asset: fonts/Montserrat-Regular.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
