// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByaH1IxWL5f4xYNXXTM4N21FfdHxacdY4',
    appId: '1:900457764149:web:248cc6bbe380cf5e14287c',
    messagingSenderId: '900457764149',
    projectId: 'temani---tracker-kehamilan',
    authDomain: 'temani---tracker-kehamilan.firebaseapp.com',
    storageBucket: 'temani---tracker-kehamilan.appspot.com',
    measurementId: 'G-9PHPS1XN9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNfD8GbGP87B8X0Hu841GS786asKLFgIc',
    appId: '1:900457764149:android:bf3b189cc209775714287c',
    messagingSenderId: '900457764149',
    projectId: 'temani---tracker-kehamilan',
    storageBucket: 'temani---tracker-kehamilan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxcgCBHgHQ-DHKHqCcVo4NsrsxgEWcmIw',
    appId: '1:900457764149:ios:d5af92fc5d705c6b14287c',
    messagingSenderId: '900457764149',
    projectId: 'temani---tracker-kehamilan',
    storageBucket: 'temani---tracker-kehamilan.appspot.com',
    androidClientId: '900457764149-hglpi5ah7p323pe75gmcr2duq5721rrl.apps.googleusercontent.com',
    iosClientId: '900457764149-31e6suk7vepjlj5sou5b7imppnkck0ri.apps.googleusercontent.com',
    iosBundleId: 'com.example.temani',
  );
}
